10/23: refactoring to make new results page error message: jquery.min.js:4  GET http://localhost:8080/fabflix_com_war/api/movies?action=getMoviesByTitle&letter=K 500 (Internal Server Error) send	@	jquery.min.js:4 ajax	@	jquery.min.js:4 fetchMovies	@	movies.js:123 (anonymous)	@	movies.js:118 j	@	jquery.min.js:2 k	@	jquery.min.js:2 setTimeout (anonymous)	@	jquery.min.js:2 i	@	jquery.min.js:2 fireWith	@	jquery.min.js:2 fire	@	jquery.min.js:2 i	@	jquery.min.js:2 fireWith	@	jquery.min.js:2 ready	@	jquery.min.js:2 S	@	jquery.min.js:3
movies.js:129 error fetching movies:
error	@	movies.js:129
i	@	jquery.min.js:2
fireWith	@	jquery.min.js:2
A	@	jquery.min.js:4
(anonymous)	@	jquery.min.js:4
load
send	@	jquery.min.js:4
ajax	@	jquery.min.js:4
fetchMovies	@	movies.js:123
(anonymous)	@	movies.js:118
j	@	jquery.min.js:2
k	@	jquery.min.js:2
setTimeout
(anonymous)	@	jquery.min.js:2
i	@	jquery.min.js:2
fireWith	@	jquery.min.js:2
fire	@	jquery.min.js:2
i	@	jquery.min.js:2
fireWith	@	jquery.min.js:2
ready	@	jquery.min.js:2
S	@	jquery.min.js:3